### PR TITLE
Feature/7 complete services card

### PR DESCRIPTION
**Pull request by thuan734655**
completed section services-card

### CODE REVIEW

**Comment by DatWithTheWorld** [comment]
> completed section services-card

push your screenshot website in your comment

**Comment by thuan734655** [comment]
image
image

**Comment by thuan734655** [comment]
Because my cloudy icon file was in the wrong branch, it couldn't find the link, causing an error. Thanks

**Comment by DatWithTheWorld** [comment]
They should have the same size. why u set with and height for each them

**Comment by thuan734655** [comment]
Because I use the px-to-vw function for each screen type, I have to resize them according to each screen type.

**Pull request closed without merging**
